apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-store
  template:
    metadata:
      labels:
        app:  book-store
    spec:
      containers:
        - name:  book-store
          image:  book-store:latest  
          ports:
            - containerPort: 80
