apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-store
  template:
    metadata:
      labels:
        app: book-store
    spec:
      containers:
        - name: book-store
          image: book-store:latest  
          ports:
            - containerPort: 80
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: app-secret
            - name: JWT_SECRET_ISSUER
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_ISSUER
                  name: app-secret
            - name: JWT_SECRET_AUDIENCE
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_AUDIENCE
                  name: app-secret
