apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  JWT_SECRET: YourSuperBaddassSecretKeyHereThatIsAtLeast16BytesN3Q5dDN0MzR2ZmZkZmRmamRmamRuZmowMnJpMDRy
  JWT_SECRET_ISSUER: localhost
  JWT_SECRET_AUDIENCE: api